spring.datasource.url=jdbc:mysql://localhost:3306/styler_db?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=dante
spring.datasource.password=1234

# A strong, random secret key (use at least 256 bits/32 characters)
jwt.secret=af253c1f853284cca9d8c6e0e2b33770e0236184f856b752b3e26c85008041ed

# Token expiration time in milliseconds (e.g., 10 hours = 36000000 ms)
jwt.expirationMs=36000000

# Max size for a single file
spring.servlet.multipart.max-file-size=5MB

# Max total request size (3 images x 5MB + other fields)
spring.servlet.multipart.max-request-size=20MB

logging.level.org.springframework.security=DEBUG



